function Hd = fir_filter_design_2
%FIR_FILTER_DESIGN_2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
% Generated on: 31-Jul-2021 17:47:50

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 10000;  % Sampling Frequency

Fpass = 1;             % Passband Frequency
Fstop = 150;           % Stopband Frequency
Dpass = 0.9801980198;  % Passband Ripple
Dstop = 0.001;         % Stopband Attenuation
flag  = 'scale';       % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fpass Fstop]/(Fs/2), [1 0], [Dstop Dpass]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);
% Set the arithmetic property.
set(Hd, 'Arithmetic', 'fixed', ...
    'CoeffWordLength', 16, ...
    'CoeffAutoScale', true, ...
    'Signed',         true, ...
    'InputWordLength', 16, ...
    'inputFracLength', 15, ...
    'FilterInternals',  'FullPrecision');
denormalize(Hd);


% [EOF]
